[package]
name = "rnmap"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "rnmap CLI: standalone Rust port scanner"

[[bin]]
name = "rnmap"
path = "src/main.rs"

[dependencies]
rnmap-core = { path = "../rnmap-core" }
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde_json.workspace = true
dns-lookup.workspace = true
